"""The shared legacy-approval scenario behind the v1.9 golden-log test.

One deterministic run exercising every legacy approval-routing surface
that existed BEFORE the v1.9 authority-ceiling work, with a frozen
clock and a fixed run id so the produced event log is byte-for-byte
reproducible:

  * a pack whose ``PackPolicy(requires_approval=...)`` gates an object
    type, with capabilities declared via ``risk_class`` ONLY (no
    ``action_class`` anywhere — that is the point of the regression);
  * a behavior that trips the gate through ``ctx.propose_object``;
  * ``pending_approvals()`` + ``approve()`` materializing the deferred
    object (the v1.4 graph-backed approval flow).

``tests/snapshots/legacy_approval_log.jsonl`` was generated by running
exactly this scenario on the pre-v1.9 tree (commit before the authority
work), via ``scenario_log_lines()``. The regression test re-runs the
scenario on the current tree and compares byte-for-byte: a v1.9 change
that alters ANY legacy event — order, payload, id, or count — or that
emits any new event on this path, fails the test. CONTRACT v1.9
("deliberately does NOT touch": existing static approval configuration
behaves byte-identically when the new API is not called).
"""

from __future__ import annotations

import json

from activegraph import Graph, Runtime
from activegraph.core.clock import FrozenClock
from activegraph.packs import Pack, PackPolicy, behavior
from activegraph.packs.manifest import CapabilityDecl
from pydantic import BaseModel


class _Doc(BaseModel):
    """Schema for the gated object type."""

    title: str = ""


class _Note(BaseModel):
    """Schema for the trigger object type."""

    text: str = ""


def _build_pack() -> Pack:
    """The legacy pack: risk_class-only capabilities, one approval gate."""
    from activegraph.packs import ObjectType

    @behavior(
        name="legacy_proposer",
        on=["object.created"],
        where={"object.type": "note"},
        creates=["doc"],
    )
    def legacy_proposer(event, graph, ctx):  # type: ignore[no-untyped-def]
        """Propose a gated doc for every note (routes via approval)."""
        obj = event.payload.get("object", {})
        ctx.propose_object(
            "doc",
            {"title": f"draft for {obj.get('id', '?')}"},
            reason="legacy scenario",
        )

    return Pack(
        name="legacy_scenario",
        version="0.1.0",
        description="risk_class-only pack for the byte-identical regression",
        object_types=(
            ObjectType(name="note", schema=_Note, description="trigger"),
            ObjectType(name="doc", schema=_Doc, description="gated"),
        ),
        behaviors=(legacy_proposer,),
        policies=(
            PackPolicy(name="gate_docs", requires_approval=("doc",)),
        ),
        capabilities=(
            CapabilityDecl(
                provider="legacy",
                capability="lookup",
                risk_class="low",
            ),
            CapabilityDecl(
                provider="legacy",
                capability="mutate",
                risk_class="high",
            ),
        ),
    )


def scenario_log_lines() -> list[str]:
    """Run the scenario and return the event log as JSON lines."""
    graph = Graph(clock=FrozenClock("2026-07-09T00:00:00Z"), run_id="run_LEGACY_GOLDEN")
    rt = Runtime(graph)
    rt.load_pack(_build_pack())
    graph.add_object("note", {"text": "hello"})
    rt.run_until_idle()
    pending = rt.pending_approvals()
    assert len(pending) == 1, f"expected 1 pending approval, got {len(pending)}"
    rt.approve(pending[0].id, approved_by="owner")
    rt.run_until_idle()
    return [
        json.dumps(ev.to_dict(), sort_keys=True) for ev in graph.events
    ]


if __name__ == "__main__":
    for line in scenario_log_lines():
        print(line)
