"""Execution-layer error leaves. v1.0 PR-D — ExecutionError category.

The two carrier leaves (:class:`LLMBehaviorError`,
:class:`ToolError`) live in their topic modules (``activegraph/llm/errors.py``
and ``activegraph/tools/errors.py``) because the per-reason prose
tables are co-located with the modules that raise them. This module
holds the runtime-internal execution-layer leaves that don't fit
cleanly into either topic.

PR-D adds:

- :class:`ApprovalNotFoundError` — pending-approval lookup miss.

PR-F adds (cross-category audit findings — sites that looked like
ConfigurationError on the PR-E hand-off list but classified as
ExecutionError on closer reading):

- :class:`RuntimeContextRequiredError` — ``ctx.propose_object`` was
  called from a behavior whose context wasn't bound to a runtime.
  Fires inside a running behavior, not at construction time.
- :class:`InvalidPatchLifecycleState` — ``graph.apply_patch`` was
  called on a patch that isn't in ``"proposed"`` state. Fires during
  the patch lifecycle, mid-execution.

PR-G adds:

- :class:`InternalEvaluatorError` — for the view-filter evaluator in
  ``graph.py``. Sibling to the two pattern-evaluator internal-bug
  raises in ``activegraph/runtime/patterns.py``; uses the shared
  :func:`activegraph.errors.internal_bug_fields` helper so the
  framework-bug prose is uniform across all three sites.
"""

from __future__ import annotations

from typing import Any, Optional

from activegraph.errors import DOCS_BASE_URL, ExecutionError


class ApprovalNotFoundError(ExecutionError, LookupError):
    """Pending-approval lookup miss.

    Fires from ``runtime.approve(approval_id)`` when the id doesn't
    refer to any currently-pending approval. Multi-inherits
    :class:`LookupError` so user code that does ``except LookupError``
    around the approval API continues to work.
    """

    _doc_slug = "approval-not-found-error"

    def __init__(
        self,
        approval_id: str,
        *,
        pending_count: Optional[int] = None,
    ) -> None:
        self.approval_id = approval_id
        self.pending_count = pending_count
        ctx: dict[str, Any] = {"approval_id": approval_id}
        if pending_count is not None:
            ctx["pending_count"] = pending_count
        pending_hint = (
            f"There are currently {pending_count} pending approvals; "
            f"none of them match {approval_id!r}."
            if pending_count is not None
            else "There are no pending approvals in this runtime."
        )
        ExecutionError.__init__(
            self,
            f"no pending approval named {approval_id!r}",
            what_failed=(
                f"runtime.approve({approval_id!r}) could not find a pending "
                f"approval with that id.\n  {pending_hint}"
            ),
            why=(
                "Approval ids are generated by the runtime when a behavior "
                "calls ctx.propose_object under a gating policy "
                "(memo_approval, risk_approval, etc.). Each id is unique "
                "to its runtime instance and is consumed when approve() "
                "succeeds. A miss means either the id is stale (already "
                "approved or denied), the runtime instance is fresh "
                "(approvals don't carry across Runtime.load), or the id is "
                "a typo. The framework refuses to no-op an unknown id "
                "because that would silently corrupt the approval audit "
                "trail."
            ),
            how_to_fix=(
                "List the currently-pending approvals:\n"
                "    rt.pending_approvals()\n"
                "to confirm what's actually pending. The diligence demo's\n"
                "step_2_approval_demo (examples/diligence_real_run.py)\n"
                "shows the canonical pattern: enumerate, then approve by id."
            ),
            context=ctx,
        )


class RuntimeContextRequiredError(ExecutionError, RuntimeError):
    """``ctx.propose_object`` (or another ctx method that requires the
    runtime) was called from a behavior whose context isn't bound to a
    runtime.

    Fires at execution time, inside a running behavior — the caller is
    the behavior body that invoked the ctx method, not the framework's
    construction code. Multi-inherits :class:`RuntimeError` for
    back-compat.
    """

    _doc_slug = "runtime-context-required-error"

    def __init__(self, *, method: str = "ctx.propose_object") -> None:
        self.method = method
        ExecutionError.__init__(
            self,
            f"{method} requires a runtime-bound context",
            what_failed=(
                f"A behavior called {method} on a BehaviorGraph context that "
                f"was constructed without a Runtime — likely a test fixture "
                f"that stubbed the graph without going through Runtime."
            ),
            why=(
                "ctx.propose_object writes to the runtime's pending-approvals "
                "queue and emits a `approval.proposed` event. Without a "
                "runtime, neither side effect can happen, and a no-op would "
                "silently break the policy gate the behavior depends on — "
                "the audit trail would show no proposal and the operator "
                "would have no record to approve.\n"
                "\n"
                f"See {DOCS_BASE_URL}/concepts/failure-model "
                f"for when the framework prefers exceptions over silent no-ops."
            ),
            how_to_fix=(
                "Construct the BehaviorGraph through a Runtime:\n"
                "    rt = Runtime(graph, ...)\n"
                "    rt.run_goal('...')   # behaviors see ctx bound to rt\n"
                "\n"
                "In a test, drive the behavior through a real Runtime — the "
                "ctx is built from the runtime's context factory and bound "
                "automatically. Mocking the ctx directly bypasses this; if "
                "the test really needs to bypass the runtime, mock the "
                "policy gate as well so propose_object isn't reached."
            ),
            context={"method": method},
        )


class InvalidPatchLifecycleState(ExecutionError, ValueError):
    """``graph.apply_patch(patch_id)`` was called on a patch that isn't
    in ``"proposed"`` state.

    Patches go through ``proposed → applied`` (success) or ``proposed →
    rejected`` (policy or behavior rejection). Calling ``apply_patch``
    on an already-applied or already-rejected patch is a programmer
    error in the calling code path; the framework refuses rather than
    re-apply or silently no-op. Multi-inherits :class:`ValueError`.
    """

    _doc_slug = "invalid-patch-lifecycle-state"

    def __init__(self, *, patch_id: str, current_status: str) -> None:
        self.patch_id = patch_id
        self.current_status = current_status
        ExecutionError.__init__(
            self,
            f"patch {patch_id} is {current_status!r}, not 'proposed'",
            what_failed=(
                f"graph.apply_patch({patch_id!r}) was called, but the patch's "
                f"current status is {current_status!r}. Only patches in the "
                f"'proposed' state can be applied."
            ),
            why=(
                "Patches are one-shot: a 'proposed' patch becomes 'applied' "
                "(success) or 'rejected' (refusal) exactly once. Re-applying "
                "an already-applied patch would emit a duplicate "
                "`patch.applied` event, which would break the replay "
                "contract — replay would produce a different event stream "
                "than the original run. The framework refuses re-application "
                "rather than emit the duplicate.\n"
                "\n"
                f"See {DOCS_BASE_URL}/concepts/failure-model "
                f"for the patch-lifecycle invariants."
            ),
            how_to_fix=(
                f"Check the patch's current status before applying:\n"
                f"    patch = graph.get_patch({patch_id!r})\n"
                f"    if patch.status == 'proposed':\n"
                f"        graph.apply_patch({patch_id!r})\n"
                f"\n"
                f"If the patch is already applied and the caller wants a "
                f"new mutation, propose a new patch — patches don't get "
                f"re-used."
            ),
            context={"patch_id": patch_id, "current_status": current_status},
        )


class InternalEvaluatorError(ExecutionError, ValueError):
    """A framework-internal evaluator received input it does not
    recognize. Should not fire in normal use — the framework's parsers
    produce a closed set of operators / AST nodes, and an unrecognized
    one means either drift between parser and evaluator or external
    AST construction that bypassed the parser.

    Multi-inherits :class:`ValueError` so user code that catches the
    builtin around view operations continues to work. Used by
    ``activegraph/core/graph.py`` for the view-filter evaluator; the
    pattern-subscription evaluator's two internal-bug raises stay as
    :class:`UnsupportedPatternError` (the natural category) but use
    the same :func:`activegraph.errors.internal_bug_fields` helper so
    the prose is uniform across all three sites.
    """

    _doc_slug = "internal-evaluator-error"

    def __init__(
        self,
        summary: str,
        *,
        what_failed: str,
        why: str,
        how_to_fix: str,
        context: Optional[dict[str, Any]] = None,
    ) -> None:
        ExecutionError.__init__(
            self,
            summary,
            what_failed=what_failed,
            why=why,
            how_to_fix=how_to_fix,
            context=context,
        )


class ReservedFieldError(ExecutionError, ValueError):
    """Caller-supplied object/patch data used a framework-reserved key.

    Fires from ``graph.add_object`` / ``add_relation`` /
    ``patch_object`` / ``propose_patch`` when the ``data`` / ``updates``
    / ``value`` dict contains a reserved top-level key (today:
    ``provenance``). CONTRACT v1.10 #2: before v1.10 the reserved key
    was silently stripped — a caller who thought they attached
    provenance had attached nothing. The framework now refuses loudly
    so the data loss is visible at the call site. Multi-inherits
    :class:`ValueError` so ``except ValueError`` call sites keep
    working.
    """

    _doc_slug = "reserved-field-error"

    def __init__(self, *, field: str, api: str, param: str) -> None:
        self.field = field
        self.api = api
        self.param = param
        ExecutionError.__init__(
            self,
            f"reserved field {field!r} in graph.{api}() {param}",
            what_failed=(
                f"graph.{api}(...) received a {param} dict containing the "
                f"key {field!r}. That key is reserved: the framework writes "
                f"it on every object, relation, and patch, and caller data "
                f"cannot set or shadow it."
            ),
            why=(
                "Provenance is stamped by the runtime, never by the caller "
                "(CONTRACT #5) — it records who created an entity, which "
                "event caused it, and in which run, and its integrity is "
                "what makes causal chains and replay audits trustworthy. "
                "Before v1.10 a caller-supplied 'provenance' key was "
                "silently dropped, so code that believed it had attached "
                "provenance had attached nothing, with no signal. The "
                "framework now fails loudly instead: there is no case "
                "where passing the reserved key is correct, so tolerating "
                "it only preserves the silent data loss.\n"
                "\n"
                f"See {DOCS_BASE_URL}/concepts/failure-model "
                f"for when the framework prefers exceptions over silent "
                f"no-ops."
            ),
            how_to_fix=(
                "Pick the channel that matches your intent:\n"
                "  - To influence what provenance records, use the "
                "sanctioned kwargs:\n"
                "        graph.add_object(type, data, actor=..., "
                "caused_by=..., evidence=[...])\n"
                "    (behaviors get actor/caused_by stamped automatically "
                "by their BehaviorGraph).\n"
                "  - To read provenance, use the handle: obj.provenance.\n"
                "  - If the key is genuinely your domain data (e.g. a "
                "document's own chain of custody), rename it — "
                "'source_provenance', 'chain_of_custody' — so it cannot "
                "shadow the framework field."
            ),
            context={"field": field, "api": api, "param": param},
        )


class PromoteLineageError(ExecutionError, ValueError):
    """The promote source is not a direct fork of the destination.

    Fires from ``runtime.promote(fork)`` when the store's run records
    say ``fork``'s run did not fork from this runtime's run — an
    unrelated run, a grandchild (promote goes up one level at a
    time), or a run whose fork point isn't in this parent's log.
    CONTRACT v1.3 #4.
    """

    _doc_slug = "promote-lineage-error"

    def __init__(
        self,
        *,
        from_run: str,
        into_run: str,
        recorded_parent: Optional[str],
        detail: str,
    ) -> None:
        self.from_run = from_run
        self.into_run = into_run
        self.recorded_parent = recorded_parent
        ExecutionError.__init__(
            self,
            f"run {from_run!r} is not a direct fork of {into_run!r}",
            what_failed=(
                f"runtime.promote() was asked to promote run "
                f"{from_run!r} into run {into_run!r}, but the store's "
                f"lineage records disagree: {detail}"
            ),
            why=(
                "Promote applies a fork's net delta three-way against "
                "the parent's state at the recorded fork point, so the "
                "source must be a DIRECT fork of the destination — the "
                "runs table's parent_run_id / forked_at_event_id row is "
                "the authority, not the caller's claim. Fork-of-fork "
                "lineages promote one level at a time (CONTRACT v1.3 #4)."
            ),
            how_to_fix=(
                "Check the lineage with:\n"
                "    activegraph inspect <store> --runs\n"
                "\n"
                "For a grandchild fork, promote into its own parent "
                "first, then promote that parent one level up. For an "
                "unrelated run there is nothing to promote: fork from "
                "the destination run and re-apply the change there."
            ),
            context={
                "from_run": from_run,
                "into_run": into_run,
                "recorded_parent": recorded_parent,
            },
        )


class PromoteConflictError(ExecutionError, ValueError):
    """The fork's delta conflicts with the parent's own post-fork work.

    Fires from ``runtime.promote(fork)`` before ANY mutation: one
    conflict fails the whole promote (fail-closed, atomic — CONTRACT
    v1.3 #4). Carries the full conflict list on ``.conflicts`` (the
    same ``PromoteConflict`` records a ``dry_run`` plan exposes).
    """

    _doc_slug = "promote-conflict-error"

    def __init__(self, *, conflicts: list[Any], from_run: str, into_run: str) -> None:
        self.conflicts = list(conflicts)
        self.from_run = from_run
        self.into_run = into_run
        preview = "\n".join(
            f"    [{c.kind}] {c.entity} {c.id}: {c.detail}"
            for c in self.conflicts[:8]
        )
        more = (
            f"\n    ... and {len(self.conflicts) - 8} more"
            if len(self.conflicts) > 8
            else ""
        )
        ExecutionError.__init__(
            self,
            f"{len(self.conflicts)} conflict(s) block promoting "
            f"{from_run!r} into {into_run!r}",
            what_failed=(
                f"runtime.promote() found {len(self.conflicts)} "
                f"conflict(s) between the fork's delta and the parent's "
                f"own changes since the fork point:\n{preview}{more}"
            ),
            why=(
                "Promote is fail-closed and atomic: an entity changed on "
                "both sides since the fork point (or a promoted relation/"
                "removal that would break referential integrity) means a "
                "human or a higher layer decides — the runtime does no "
                "semantic merging, and nothing was applied "
                "(CONTRACT v1.3 #4)."
            ),
            how_to_fix=(
                "Inspect the full list first:\n"
                "    plan = parent.promote(fork, dry_run=True)\n"
                "    for c in plan.conflicts: print(c.kind, c.id, c.detail)\n"
                "\n"
                "The escape hatch is the loop itself, not a force flag: "
                "fork again from the parent's current tip, re-apply the "
                "candidate change there (caches make the shared prefix "
                "cheap), and promote the fresh fork — that re-tests the "
                "change against the parent's actual present."
            ),
            context={
                "from_run": from_run,
                "into_run": into_run,
                "conflict_count": len(self.conflicts),
                "conflict_kinds": sorted({c.kind for c in self.conflicts}),
            },
        )
